# Copyright 2020, 2025, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence .NET Extend Client GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: CI Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
  push:
    branches:
    - main
  pull_request:
    types:
      - opened
      - committed
    branches:
    - main
    - '*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

      # Set up .NET versions
    - name: Set up dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x

    # Clean
    - name: Clean
      run: dotnet nuget locals all --clear

    # Build
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

  test-linux:
    name: Test on Linux against Coherence ${{ matrix.coherence_version }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coherence_version: [25.09]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Set up .NET versions
    - name: Set up dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          8.x

    # Set up Java 21
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-

    # Build Coherence
    - name: Build Coherence
      run: |
        echo "Building Coherence"
        # pushd tests/coherence/prj
        # mvn clean install -DskipTests
        # source ~/work/coherence-dotnet-extend-client/coherence-dotnet-extend-client/tests/coherence/envconfig/cfglocal.sh
        # export DEV_ROOT=$(pwd)
        # export SETTINGS_XML=${DEV_ROOT}/.github/maven/settings.xml
        # mvn clean install -T 1.5C -U -Dgradle.skip.test=true -DskipTests
        # mvn --file prj/pom.xml --batch-mode -U -e -s ${SETTINGS_XML} -P-modules -Doptional -DskipTests -Dcoherence.SkipLargeMemoryTests=true clean install
        # mvn --file prj/pom.xml --batch-mode -e -s ${SETTINGS_XML} -Pmodules,-coherence -nsu -Doptional -DskipTests -Dcoherence.SkipLargeMemoryTests=true -Dcoherence.compatability.settings=${SETTINGS_XML} clean install
        # popd
        pushd tests/install
        mvn install:install-file -Dfile=coherence-25.09.jar -DgroupId=com.oracle.coherence.ce -DartifactId=coherence -Dversion=25.09 -Dpackaging=jar
        mvn install:install-file -Dfile=jakarta.el-api-5.0.1.jar -DgroupId=jakarta.el -DartifactId=jakarta.el-api -Dversion=5.0.1 -Dpackaging=jar
        popd

    # Build
    - name: Build
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    # Build test server
    - name: Build test server
      run: |
        pushd tests/test-server
        mvn --batch-mode -e clean install -s .mvn/settings.xml -Drevision=${{ matrix.coherence_version }} -Dcoherence.groupid=com.oracle.coherence.ce -Dmain=com.tangosol.net.DefaultCacheServer
        popd

    # Start test server
    - name: Start test server
      run: |
        pushd tests/test-server
        mvn --batch-mode -e exec:exec -s .mvn/settings.xml -Drevision=${{ matrix.coherence_version }} -Dcoherence.groupid=com.oracle.coherence.ce -Dmain=com.tangosol.net.DefaultCacheServer &
        sleep 30
        popd
        
    # Start test server
    - name: Start test server
      run: |
        pushd tests/test-server
        mvn --batch-mode -e exec:exec -s .mvn/settings.xml -Drevision=${{ matrix.coherence_version }} -Dcoherence.groupid=com.oracle.coherence.ce -Dmain=com.tangosol.net.DefaultCacheServer -Dexec.args="-Dcoherence.log=DefaultCacheServer2.log -Dcoherence.log.level=6 -Dtangosol.coherence.proxy.port=12345 -Dcoherence.proxy.port1=3001 -Dtangosol.coherence.proxy.port5=3002 -Dtangosol.coherence.proxy.port4=3003 -Dtangosol.coherence.proxy.port2=3004 -Dtangosol.coherence.proxy.port11=3005 -Dtangosol.coherence.proxy.port12=3006 -Dtangosol.coherence.proxy.port7=3007 -Dtangosol.coherence.proxy.port9=3008 -Dtangosol.coherence.proxy.port8=3009 -Dcoherence.management=all -Dcoherence.health.http.port=33333 -Dtangosol.coherence.messaging.debug=true -cp %classpath com.tangosol.net.Coherence" &
        sleep 30
        popd

    - name: Retry curl until cluster is ready
      id: curl_check
      run: |
        max_attempts=60
        attempt=1
        url="http://localhost:33333/ready"
        expected_response="200"
        
        while [ $attempt -le $max_attempts ]; do
          response=$(curl -s -o /dev/null -w %{http_code} "$url")
          echo "Attempt $attempt: Response - $response"

          if [ "$response" != "$expected_response" ]; then
            echo "Received incorrect response. Retrying..."
            sleep 5
          else
            echo "Correct response received. Exiting..."
            exit 0
          fi

          sleep 5
          attempt=$((attempt + 1))
        done

        echo "All attempts failed."
        exit 1  # Fails the step if all attempts fail

    # Run Tests
    - name: Run Tests
      run: dotnet test --filter FullyQualifiedName\!~Tangosol.Web --configuration Release --no-restore

    # Capture server log for diagnosing failures
    - name: Capture test logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.os }}-${{ matrix.coherence_version }}
        path: |
          build/
          ~/work/coherence-dotnet-extend-client/coherence-dotnet-extend-client/tests/test-server/
          ~/work/coherence-dotnet-extend-client/coherence-dotnet-extend-client/build/
        compression-level: 9

